financials_list = [\
'GrossProfit',\
'CostOfRevenue',\
'OperatingRevenue',\
'Revenues',\
'OperatingIncomeLoss',\
'NetIncomeLoss',\
'ResearchAndDevelopment',\
'OperatingExpenses',\
'AssetsCurrent',\
'Assets',\
'LiabilitiesCurrent',\
'Liabilities',\
'CashAndCashEquivalentsAtCarryingValue',\
'LongTermDebtCurrent',\
'LongTermDebtNoncurrent',\
'TotalCash',\
'Cash',\
'RevenueFromContractWithCustomerExcludingAssessedTax',\
'TotalDebt',\
'ShareholderEquity',\
'CashAndCashEquivalentsPeriodIncreaseDecrease',\
'CommonStockDividendsPerShareDeclared',\
'CommonStockDividendsPerShareCashPaid',\
'CommonStockSharesOutstanding',\
'WeightedAverageNumberOfSharesOutstandingBasic',\
'SharesOutstanding',\
'EarningsPerShareBasic']